# Generated by Django 4.2.5 on 2023-10-02 16:12

from django.db import migrations, models
import elevator.models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the elevator", max_length=30),
                ),
                (
                    "state",
                    enumchoicefield.fields.EnumChoiceField(
                        default=elevator.models.ElevatorState["IDLE"],
                        enum_class=elevator.models.ElevatorState,
                        help_text="Shows the current state of Elevator",
                        max_length=17,
                    ),
                ),
                (
                    "total_number_of_floors",
                    models.IntegerField(
                        default=1, help_text="Number of floors in the building"
                    ),
                ),
                (
                    "floors_not_in_use",
                    models.JSONField(
                        blank=True,
                        help_text="Floors that are not in use. Elevator will not stop on these floors",
                        null=True,
                    ),
                ),
                (
                    "capacity_in_person",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of people allowed in the elevator",
                    ),
                ),
                (
                    "current_floor",
                    models.IntegerField(help_text="Show the current floor"),
                ),
            ],
        ),
    ]
