# Generated by Django 4.2.5 on 2023-10-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pick_from_floor_number",
                    models.IntegerField(
                        default=0, help_text="Floor number where the elevator is called"
                    ),
                ),
                (
                    "drop_at_floor_number",
                    models.IntegerField(
                        default=0, help_text="Floor number passenger wants to go to"
                    ),
                ),
                (
                    "number_of_passengers",
                    models.IntegerField(
                        default=0,
                        help_text="Number of passengers that are waiting for the elevator",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Shows if the request is completed"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the request was created",
                    ),
                ),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elevatorrequest",
                        to="elevator.elevator",
                    ),
                ),
            ],
        ),
    ]
